// Demo data for a LOCAL database only: made-up players with picks on the real
// results so far, a private league, and the crowd forecasts that follow.
// Used to record the demo video. Never run it against the real database.
//
//   npm run demo:seed     (after npm run db:migrate:local and one sync)

import { parseFeed, SEASON } from '../src/data/openfootball'
import { BASE_RATES, OUTCOMES, outcomeFromScore, points, type League, type Outcome, type Probs } from '../src/scoring/scoring'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = join(import.meta.dirname, '..')
const OUT = process.argv[2] ?? join(ROOT, '.wrangler', 'demo-seed.sql')

// "you" in the demo is the Pi stub's user; the rest are made-up players.
const YOU = { id: 'pi:u-james', username: 'james', skill: 0.3 }
const PLAYERS = [
  ['ada_lagos', 0.34], ['tunde_fc', 0.22], ['minh_hcm', 0.3], ['grace_mnl', 0.18], ['arjun_k', 0.26],
  ['siti_jkt', 0.2], ['kwame_acc', 0.12], ['linh_hn', 0.28], ['paolo_ceb', 0.1], ['chioma', 0.24],
  ['rahul_pune', 0.16], ['dewi_bdg', 0.3], ['emeka', 0.06], ['bao_dn', 0.2],
].map(([name, skill]) => ({ id: `fake:${name}`, username: name as string, skill: skill as number }))

let seed = 2026
function rand() {
  seed = (seed * 1103515245 + 12345) & 0x7fffffff
  return seed / 0x80000000
}

/**
 * A plausible forecast: base rates, pulled toward the real result by skill,
 * plus noise. Tuned so averages land where real football forecasters do: a
 * few points either side of the base rate's ~68.
 */
function forecast(base: Probs, actual: Outcome, skill: number): Probs {
  const edge = skill * 0.25
  const raw = OUTCOMES.map((o) => Math.max(0.02, base[o] + (o === actual ? edge : -edge / 2) + (rand() - 0.5) * 0.4))
  const sum = raw.reduce((a, b) => a + b, 0)
  const pct = raw.map((v) => Math.floor((v / sum) * 100))
  pct[pct.indexOf(Math.max(...pct))] += 100 - pct.reduce((a, b) => a + b, 0)
  return { H: pct[0], D: pct[1], A: pct[2] }
}

const q = (s: string) => `'${s.replace(/'/g, "''")}'`
const sql: string[] = ['-- Demo data (local only). Generated by scripts/demo-seed.ts.']
for (const u of [YOU, ...PLAYERS]) {
  sql.push(`INSERT OR IGNORE INTO users (id, username, created_at) VALUES (${q(u.id)}, ${q(u.username)}, 0);`)
}

let count = 0
for (const league of ['en.1', 'es.1'] as League[]) {
  const json = JSON.parse(readFileSync(join(ROOT, 'src/data/__fixtures__', `2026-27-${league}.json`), 'utf8'))
  for (const f of parseFeed(league, SEASON, json).fixtures) {
    if (!f.score) continue
    const actual = outcomeFromScore(f.score[0], f.score[1])
    for (const u of [YOU, ...PLAYERS]) {
      if (rand() < 0.12) continue // nobody picks every match
      const p = forecast(BASE_RATES[league], actual, u.skill)
      const at = f.kickoffAt - Math.floor(rand() * 72 * 3600_000) - 600_000
      sql.push(
        `INSERT OR REPLACE INTO picks (user_id, match_id, h, d, a, points, created_at, updated_at) VALUES ` +
          `(${q(u.id)}, ${q(f.id)}, ${p.H}, ${p.D}, ${p.A}, ${points(p, actual)}, ${at}, ${at});`,
      )
      count++
    }
  }
}

// The crowd forecast is fixed at settlement; recompute it now the picks exist.
sql.push(`UPDATE matches SET
  crowd_h = (SELECT avg(h) FROM picks WHERE match_id = matches.id),
  crowd_d = (SELECT avg(d) FROM picks WHERE match_id = matches.id),
  crowd_a = (SELECT avg(a) FROM picks WHERE match_id = matches.id),
  crowd_n = (SELECT count(*) FROM picks WHERE match_id = matches.id)
  WHERE status = 'settled';`)

// A private league with some of them in it (no payment row: it's demo data).
sql.push(`INSERT OR IGNORE INTO leagues (id, name, invite_code, owner_id, order_id, created_at)
  VALUES ('demo-league', 'Lagos Office Five', 'LAGS5FC2', 'fake:ada_lagos', NULL, 0);`)
for (const name of ['ada_lagos', 'tunde_fc', 'chioma', 'emeka', 'kwame_acc']) {
  sql.push(`INSERT OR IGNORE INTO league_members VALUES ('demo-league', 'fake:${name}', 0);`)
}

writeFileSync(OUT, sql.join('\n') + '\n')
console.log(`${count} picks for ${PLAYERS.length + 1} players → ${OUT}`)
